apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-wildcard-host
spec:
  rules:
  - host: "app.trythat.aribadevops.site"
    http:
      paths:
      - pathType: Prefix
        backend:
          service:
            name: service1
            port:
              number: 80

  - host: "bknd.trythat.aribadevops.site"
    http:
      paths:
      - pathType: Prefix
        backend:
          service:
            name: service2
            port:
              number: 8000


  - host: "Trythat.aribadevops.site"
    http:
      paths:
      - pathType: Prefix
        path: "/foo"
        backend:
          service:
            name: service3
            port:
              number: 80
