apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: web-app:networking.k8s.io/Ingress:ingress-nginx/new-app-dep-on-eks
  name: new-app-dep-on-eks
  namespace: trythat-app
spec:
  rules:
    - host: app.trythat.aribadevops.site
      http:
        paths:
          - backend:
              service:
                name: frontend
                port:
                  number: 80
            path: /
            pathType: Prefix
    - host: bknd.trythat.aribadevops.site
      http:
        paths:
          - backend:
              service:
                name: backend
                port:
                  number: 8000
            path: /
            pathType: Prefix
    - host: trythat.aribadevops.site
      http:
        paths:
          - backend:
              service:
                name: landingpage
                port:
                  number: 80
            path: /
            pathType: Prefix
