apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: trythat-ingress
  namespace: trythat-app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/use-regex: "true"
    cert-manager.io/cluster-issuer: letsencrypt-http
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - trythat.aribadevops.site
        - app.trythat.aribadevops.site
        - bknd.trythat.aribadevops.site
      secretName: trythat-app-tls
  rules:
    - host: trythat.aribadevops.site
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 80
    - host: app.trythat.aribadevops.site
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app-service
                port:
                  number: 80
    - host: bknd.trythat.aribadevops.site
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backend-service
                port:
                  number: 8000
