export enum ConfigEnv {
  NODE_ENV = 'NODE_ENV',
  PORT = 'PORT',
  LOG_LEVEL = 'LOG_LEVEL',
 
  FRONTEND_URL = 'FRONTEND_URL',
  HOST_URL = 'HOST_URL',
 
  DB_URI = 'DB_URI',
  DB_PORT = 'DB_PORT',
 
  JWT_SECRET_KEY = 'JWT_SECRET_KEY',
  JWT_EXPIRY = 'JWT_EXPIRY',
 
  TWILIO_ACCOUNT_SID = 'TWILIO_ACCOUNT_SID',
  TWILIO_AUTH_TOKEN = 'TWILIO_AUTH_TOKEN',
  TWILIO_SERVICE_SID = 'TWILIO_SERVICE_SID',
 
  MAIL_HOST = 'MAIL_HOST',
  MAIL_USER = 'MAIL_USER',
  MAIL_PASSWORD = 'MAIL_PASSWORD',
  MAIL_FROM = 'MAIL_FROM',
  MAIL_PORT = 'MAIL_PORT',
 
  LINKEDIN_CLIENTID = 'LINKEDIN_CLIENTID',
  LINKEDIN_CLIENTSECRET = 'LINKEDIN_CLIENTSECRET',
  LINKEDIN_SCOPE = 'LINKEDIN_SCOPE',
 
  GOOGLE_API_KEY = 'GOOGLE_API_KEY',
  GOOGLE_MAPS_API_URL = 'GOOGLE_MAPS_API_URL',
 
  COMETCHAT_APPID = 'COMETCHAT_APPID',
  COMETCHAT_REGION = 'COMETCHAT_REGION',
  COMETCHAT_AUTHKEY = 'COMETCHAT_AUTHKEY',
 
  R_ENGINE_HOST = 'R_ENGINE_HOST',
 
  CRM_ENCRYPTION_KEY = 'CRM_ENCRYPTION_KEY',
  CRM_ORGANIZATION = 'CRM_ORGANIZATION',
  CRM_LOGIN_KEY = 'CRM_LOGIN_KEY',
  CRM_HOST_URL = 'CRM_HOST_URL',
  CRM_UI_URL = 'CRM_UI_URL',
  CRM_SECRET_KEY = 'CRM_SECRET_KEY',
 
  AWS_ACCESS_KEY_ID = 'AWS_ACCESS_KEY_ID',
  AWS_SECRET_ACCESS_KEY = 'AWS_SECRET_ACCESS_KEY',
  IMAGE_UPLOAD_BUCKET = 'IMAGE_UPLOAD_BUCKET',
 
  OKR_SECRET_KEY = 'OKR_SECRET_KEY',
  OKR_HOST_URL = 'OKR_HOST_URL',
  OKR_UI_URL = 'OKR_UI_URL',
  OKR_ORGANIZATION = 'OKR_ORGANIZATION',
 
  SMS_API_KEY = 'SMS_API_KEY',
  SMS_SERVER_URL = 'SMS_SERVER_URL',
  SMS_USER_ID = 'SMS_USER_ID',
  SMS_PASSWORD = 'SMS_PASSWORD',
  SMS_SENDER_NAME = 'SMS_SENDER_NAME',
  SMS_DLT_ENTITY_ID = 'SMS_DLT_ENTITY_ID',
  SMS_SEND_METHOD = 'SMS_SEND_METHOD',
  SMS_MSG_TYPE = 'SMS_MSG_TYPE',
  SMS_DLT_TEMPLATE_ID = 'SMS_DLT_TEMPLATE_ID',
  SMS_OUTPUT = 'SMS_OUTPUT',
  SMS_DUPLICATE_CHECK = 'SMS_DUPLICATE_CHECK',
  SMS_PAYLOAD = 'SMS_PAYLOAD'
}
